--- 
info:
  description: "Training configuration repo"
eureka: 
  client: 
    serviceUrl: 
      defaultZone: "http://eureka:eureka123@eureka-unsmitten-town.cfapps.io/eureka"

---

spring:
  profiles: cloud
eureka: 
  instance: 
    NonSecurePort: 80
    hostname: ${vcap.application.uris[0]}